version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /etc/nginx/certs 
      - /etc/nginx/vhost.d 
      - /usr/share/nginx/html 
      - /var/run/docker.sock:/tmp/docker.sock:ro 
    ports:
      - 80:80
      - 443:443

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.example.com
